version: '3'

services:
  prisma:
    image: prismagraphql/prisma:1.22
    restart: always
    ports:
      - "4466:4466"
    env_file:
      - .env
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: postgres
            host: postgres
            user: ${DB_USER}
            password: ${DB_PASS}
            rawAccess: true
            port: 5432
            migrations: true
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
